name: Test on Multiple Python Versions

on:
  workflow_call:
    inputs:
      python-version:
        description: 'List of Python versions to test'
        type: string
        required: false
        default: '["3.7","3.8","3.9","3.10","3.11"]'
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ${{ fromJson(inputs.python-version) }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install local repository
        uses: "marvin-kluge/test3/.github/actions/install-local-repo@main"
      - name: Run Tests
        run: |
          pytest tests/

  inputs:
    python-version:
